version: '3'

services:

  web:
    labels:
      shipyard.route: '/'
    build: '.'
    environment:
      DATABASE_URL: 'postgres://obscure-user:obscure-password@localstack/app'
      DEV: ${DEV}
      FLASK_DEBUG: '1'
      LOCALSTACK_HOST: 'localstack'
    volumes:
      - './filesystem/entrypoints:/entrypoints:ro'
      - './migrations:/srv/migrations'
      - './src:/srv/src:ro'
    ports:
      - '8080:8080'

  worker:
    labels:
      shipyard.before: 'poetry run flask db upgrade'
    depends_on:
      - localstack
    build: '.'
    environment:
      # DATABASE_URL: 'postgres://obscure-user:obscure-password@postgres/app'
      DATABASE_URL: 'postgres://obscure-user:obscure-password@localstack/app'
      DEV: ${DEV}
      FLASK_DEBUG: '1'
      LOCALSTACK_HOST: 'localstack'
    command: '/entrypoints/worker.sh'
    volumes:
      - './filesystem/entrypoints:/entrypoints:ro'
      - './migrations:/srv/migrations'
      - './src:/srv/src:ro'

  # postgres:
  #   image: 'postgres:9.6-alpine'
  #   environment:
  #     POSTGRES_USER: 'obscure-user'
  #     POSTGRES_PASSWORD: 'obscure-password'
  #     POSTGRES_DB: 'app'
  #     PGDATA: '/var/lib/postgresql/data/pgdata'
  #   volumes:
  #     - 'postgres:/var/lib/postgresql/data'
  #   ports:
  #     - '5432'

  # redis:
  #   image: 'redis:5.0-alpine'
  #   ports:
  #     - '6379'

  localstack:
    image: 'localstack/localstack'
    ports:
      - '4566:4566'
      - '4510-4530:4510-4530'
      - '4571:4571'
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    volumes:
      - ./initaws.sh:/docker-entrypoint-initaws.d/initaws.sh

volumes:
  postgres:
